<a href="https://colab.research.google.com/github/guscldns/Attention/blob/main/fish/flsh_janghun.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## json 라벨 파일 불러오기

In [ ]:
import json
import pandas as pd

In [ ]:
with open('C:/Users/JangtangE/Documents/dataset/labels/train.json', 'r', encoding='utf-8') as json_file:
    label = json.load(json_file)

## 데이터 정제

### 데이터 확인

In [ ]:
label.keys()

dict_keys(['images', 'annotations', 'categories'])

In [ ]:
label['images'][0]

{'id': 1,
 'width': 640,
 'height': 480,
 'file_name': 'train_0.png',
 'license': 0,
 'flickr_url': '',
 'coco_url': '',
 'date_captured': 0}

In [ ]:
label['annotations'][0]

{'id': 1,
 'image_id': 1,
 'category_id': 3,
 'segmentation': [],
 'area': 40939.4791,
 'bbox': [37.98, 209.94, 369.19, 110.89],
 'iscrowd': 0,
 'attributes': {'occluded': False, 'rotation': 0.0}}

In [ ]:
label['categories'][0]

{'id': 0, 'name': '농어', 'supercategory': ''}

In [ ]:
print(len(label['images']), len(label['annotations']), len(label['categories']))

104875 6301 8

### 데이터프레임으로 변환

In [ ]:
df = pd.DataFrame(label['images'])
df

,id,width,height,file_name,license,flickr_url,coco_url,date_captured
0,1,640,480,train_0.png,0,,,0
1,3,640,480,train_1.png,0,,,0
2,4,640,480,train_2.png,0,,,0
3,5,640,480,train_3.png,0,,,0
4,6,640,480,train_4.png,0,,,0
...,...,...,...,...,...,...,...,...
104870,149812,640,480,train_104870.png,0,,,0
104871,149813,640,480,train_104871.png,0,,,0
104872,149814,640,480,train_104872.png,0,,,0
104873,149815,640,480,train_104873.png,0,,,0
104874,149816,640,480,train_104874.png,0,,,0

In [ ]:
an = pd.DataFrame(label['annotations'])
an

,id,image_id,category_id,segmentation,area,bbox,iscrowd,attributes
0,1,1,3,[],40939.4791,"[37.98, 209.94, 369.19, 110.89]",0,"{'occluded': False, 'rotation': 0.0}"
1,5,283,5,[],50205.8704,"[57.07, 247.17, 384.16, 130.69]",0,"{'occluded': False, 'rotation': 0.0}"
2,6,284,5,[],58850.5182,"[96.59, 236.87, 427.01, 137.82]",0,"{'occluded': False, 'rotation': 0.0}"
3,7,292,5,[],62936.7565,"[154.41, 254.3, 467.41, 134.65]",0,"{'occluded': False, 'rotation': 0.0}"
4,11,297,5,[],70061.3550,"[26.18, 222.61, 409.5, 171.09]",0,"{'occluded': False, 'rotation': 0.0}"
...,...,...,...,...,...,...,...,...
6296,8958,149637,3,[],35322.5680,"[35.18, 94.18, 347.8, 101.56]",0,"{'occluded': False, 'rotation': 0.0}"
6297,8959,149677,6,[],35145.8160,"[52.77, 93.05, 300.7, 116.88]",0,"{'occluded': False, 'rotation': 0.0}"
6298,8960,149678,6,[],35356.5710,"[285.39, 78.86, 296.74, 119.15]",0,"{'occluded': False, 'rotation': 0.0}"
6299,8962,149790,0,[],26736.6856,"[255.89, 216.74, 263.26, 101.56]",0,"{'occluded': False, 'rotation': 0.0}"
6300,8963,149791,0,[],14874.5205,"[476.03, 241.7, 162.83, 91.35]",0,"{'occluded': False, 'rotation': 0.0}"

In [ ]:
cate = pd.DataFrame(label['categories'])
cate

   id name supercategory
0   0   농어
1   1   베스
2   2   숭어
3   3  강준치
4   4  블루길
5   5   잉어
6   6   붕어
7   7   누치

### 데이터 프레임 합치기

In [ ]:
# 물고기 있는 데이터와 라벨 값 데이터 프레임 합치기
tr = an.merge(cate, left_on='category_id', right_on='id', how='left')
tr

,id_x,image_id,category_id,segmentation,area,bbox,iscrowd,attributes,id_y,name,supercategory
0,1,1,3,[],40939.4791,"[37.98, 209.94, 369.19, 110.89]",0,"{'occluded': False, 'rotation': 0.0}",3,강준치,
1,5,283,5,[],50205.8704,"[57.07, 247.17, 384.16, 130.69]",0,"{'occluded': False, 'rotation': 0.0}",5,잉어,
2,6,284,5,[],58850.5182,"[96.59, 236.87, 427.01, 137.82]",0,"{'occluded': False, 'rotation': 0.0}",5,잉어,
3,7,292,5,[],62936.7565,"[154.41, 254.3, 467.41, 134.65]",0,"{'occluded': False, 'rotation': 0.0}",5,잉어,
4,11,297,5,[],70061.3550,"[26.18, 222.61, 409.5, 171.09]",0,"{'occluded': False, 'rotation': 0.0}",5,잉어,
...,...,...,...,...,...,...,...,...,...,...,...
6296,8958,149637,3,[],35322.5680,"[35.18, 94.18, 347.8, 101.56]",0,"{'occluded': False, 'rotation': 0.0}",3,강준치,
6297,8959,149677,6,[],35145.8160,"[52.77, 93.05, 300.7, 116.88]",0,"{'occluded': False, 'rotation': 0.0}",6,붕어,
6298,8960,149678,6,[],35356.5710,"[285.39, 78.86, 296.74, 119.15]",0,"{'occluded': False, 'rotation': 0.0}",6,붕어,
6299,8962,149790,0,[],26736.6856,"[255.89, 216.74, 263.26, 101.56]",0,"{'occluded': False, 'rotation': 0.0}",0,농어,
6300,8963,149791,0,[],14874.5205,"[476.03, 241.7, 162.83, 91.35]",0,"{'occluded': False, 'rotation': 0.0}",0,농어,

In [ ]:
df_1 = df.copy()
label_df = df_1.merge(tr, left_on='id', right_on='image_id', how='left')
label_df

,id,width,height,file_name,license,flickr_url,coco_url,date_captured,id_x,image_id,category_id,segmentation,area,bbox,iscrowd,attributes,id_y,name,supercategory
0,1,640,480,train_0.png,0,,,0,1.0,1.0,3.0,[],40939.4791,"[37.98, 209.94, 369.19, 110.89]",0.0,"{'occluded': False, 'rotation': 0.0}",3.0,강준치,
1,3,640,480,train_1.png,0,,,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,640,480,train_2.png,0,,,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,640,480,train_3.png,0,,,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,640,480,train_4.png,0,,,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105610,149812,640,480,train_104870.png,0,,,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105611,149813,640,480,train_104871.png,0,,,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105612,149814,640,480,train_104872.png,0,,,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105613,149815,640,480,train_104873.png,0,,,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105614,149816,640,480,train_104874.png,0,,,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 데이터 정보 확인
label_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 105615 entries, 0 to 105614
Data columns (total 19 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             105615 non-null  int64
 1   width          105615 non-null  int64
 2   height         105615 non-null  int64
 3   file_name      105615 non-null  object
 4   license        105615 non-null  int64
 5   flickr_url     105615 non-null  object
 6   coco_url       105615 non-null  object
 7   date_captured  105615 non-null  int64
 8   id_x           6301 non-null    float64
 9   image_id       6301 non-null    float64
 10  category_id    6301 non-null    float64
 11  segmentation   6301 non-null    object
 12  area           6301 non-null    float64
 13  bbox           6301 non-null    object
 14  iscrowd        6301 non-null    float64
 15  attributes     6301 non-null    object
 16  id_y           6301 non-null    float64
 17  name           6301 non-null    object
 18  supercategory  6301 non-null    object
dtypes: float64(6), int64(5), object(8)
memory usage: 16.1+ MB

In [ ]:
# # # NaN값 있을때는 nan값 채우거나 삭제해야 int 변환가능(nan = 무한대)
# # NaN값 있을 때
# label_df['image_id'] = label_df['image_id'].fillna(-1).astype(int)
# label_df['image_id'] = label_df['image_id'].astype(int)
# label_df['category_id'] = label_df['category_id'].fillna(-1).astype(int)
# label_df['category_id'] = label_df['category_id'].astype(int)
# label_df['iscrowd'] = label_df['iscrowd'].fillna(-1).astype(int)
# label_df['iscrowd'] = label_df['iscrowd'].astype(int)
# label_df

# Nan 값 삭제
label_df = label_df.dropna()

In [ ]:
# NaN값 없을 때
label_df['image_id'] = label_df['image_id'].astype(int)
label_df['category_id'] = label_df['category_id'].astype(int)
label_df['iscrowd'] = label_df['iscrowd'].astype(int)
label_df

,id,width,height,file_name,license,flickr_url,coco_url,date_captured,id_x,image_id,category_id,segmentation,area,bbox,iscrowd,attributes,id_y,name,supercategory
0,1,640,480,train_0.png,0,,,0,1.0,1,3,[],40939.4791,"[37.98, 209.94, 369.19, 110.89]",0,"{'occluded': False, 'rotation': 0.0}",3.0,강준치,
185,283,640,480,train_185.png,0,,,0,5.0,283,5,[],50205.8704,"[57.07, 247.17, 384.16, 130.69]",0,"{'occluded': False, 'rotation': 0.0}",5.0,잉어,
186,284,640,480,train_186.png,0,,,0,6.0,284,5,[],58850.5182,"[96.59, 236.87, 427.01, 137.82]",0,"{'occluded': False, 'rotation': 0.0}",5.0,잉어,
192,292,640,480,train_192.png,0,,,0,7.0,292,5,[],62936.7565,"[154.41, 254.3, 467.41, 134.65]",0,"{'occluded': False, 'rotation': 0.0}",5.0,잉어,
194,297,640,480,train_194.png,0,,,0,11.0,297,5,[],70061.3550,"[26.18, 222.61, 409.5, 171.09]",0,"{'occluded': False, 'rotation': 0.0}",5.0,잉어,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105495,149637,640,480,train_104755.png,0,,,0,8958.0,149637,3,[],35322.5680,"[35.18, 94.18, 347.8, 101.56]",0,"{'occluded': False, 'rotation': 0.0}",3.0,강준치,
105524,149677,640,480,train_104784.png,0,,,0,8959.0,149677,6,[],35145.8160,"[52.77, 93.05, 300.7, 116.88]",0,"{'occluded': False, 'rotation': 0.0}",6.0,붕어,
105525,149678,640,480,train_104785.png,0,,,0,8960.0,149678,6,[],35356.5710,"[285.39, 78.86, 296.74, 119.15]",0,"{'occluded': False, 'rotation': 0.0}",6.0,붕어,
105596,149790,640,480,train_104856.png,0,,,0,8962.0,149790,0,[],26736.6856,"[255.89, 216.74, 263.26, 101.56]",0,"{'occluded': False, 'rotation': 0.0}",0.0,농어,
105597,149791,640,480,train_104857.png,0,,,0,8963.0,149791,0,[],14874.5205,"[476.03, 241.7, 162.83, 91.35]",0,"{'occluded': False, 'rotation': 0.0}",0.0,농어,

In [ ]:
print(label_df['iscrowd'].value_counts(),
      label_df['segmentation'].value_counts(),
      label_df['coco_url'].value_counts(),
      label_df['flickr_url'].value_counts(),
      label_df['date_captured'].value_counts(),
      label_df['license'].value_counts(),
      label_df['supercategory'].value_counts())

0    6301
Name: iscrowd, dtype: int64 []    6301
Name: segmentation, dtype: int64     6301
Name: coco_url, dtype: int64     6301
Name: flickr_url, dtype: int64 0    6301
Name: date_captured, dtype: int64 0    6301
Name: license, dtype: int64     6301
Name: supercategory, dtype: int64

In [ ]:
label_total = label_df.drop(['license', 'flickr_url', 'coco_url', 'date_captured','id_x', 'id_y', 'image_id', 'segmentation', 'iscrowd', 'supercategory'], axis=1)  # 또는 label_df = label_df.drop(columns=['flickr_url'], axis=1)
label_total

,id,width,height,file_name,category_id,area,bbox,attributes,name
0,1,640,480,train_0.png,3,40939.4791,"[37.98, 209.94, 369.19, 110.89]","{'occluded': False, 'rotation': 0.0}",강준치
185,283,640,480,train_185.png,5,50205.8704,"[57.07, 247.17, 384.16, 130.69]","{'occluded': False, 'rotation': 0.0}",잉어
186,284,640,480,train_186.png,5,58850.5182,"[96.59, 236.87, 427.01, 137.82]","{'occluded': False, 'rotation': 0.0}",잉어
192,292,640,480,train_192.png,5,62936.7565,"[154.41, 254.3, 467.41, 134.65]","{'occluded': False, 'rotation': 0.0}",잉어
194,297,640,480,train_194.png,5,70061.3550,"[26.18, 222.61, 409.5, 171.09]","{'occluded': False, 'rotation': 0.0}",잉어
...,...,...,...,...,...,...,...,...,...
105495,149637,640,480,train_104755.png,3,35322.5680,"[35.18, 94.18, 347.8, 101.56]","{'occluded': False, 'rotation': 0.0}",강준치
105524,149677,640,480,train_104784.png,6,35145.8160,"[52.77, 93.05, 300.7, 116.88]","{'occluded': False, 'rotation': 0.0}",붕어
105525,149678,640,480,train_104785.png,6,35356.5710,"[285.39, 78.86, 296.74, 119.15]","{'occluded': False, 'rotation': 0.0}",붕어
105596,149790,640,480,train_104856.png,0,26736.6856,"[255.89, 216.74, 263.26, 101.56]","{'occluded': False, 'rotation': 0.0}",농어
105597,149791,640,480,train_104857.png,0,14874.5205,"[476.03, 241.7, 162.83, 91.35]","{'occluded': False, 'rotation': 0.0}",농어

In [ ]:
label_total.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6301 entries, 0 to 105597
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           6301 non-null   int64
 1   width        6301 non-null   int64
 2   height       6301 non-null   int64
 3   file_name    6301 non-null   object
 4   category_id  6301 non-null   int32
 5   area         6301 non-null   float64
 6   bbox         6301 non-null   object
 7   attributes   6301 non-null   object
 8   name         6301 non-null   object
dtypes: float64(1), int32(1), int64(3), object(4)
memory usage: 467.7+ KB

In [ ]:
label_total.to_csv(r'C:/Users/JangtangE/Documents/dataset/label_total.csv', index=False)

## 라벨있는 이미지만 따로 저장

In [ ]:
import pandas as pd
import os
import shutil

# # 이미지를 저장할 디렉토리 생성
# output_directory = 'labeled_images'
# os.makedirs(output_directory, exist_ok=True)

# 데이터 프레임 반복
for index, row in label_total.iterrows():
    label = row['file_name']

    image_path = f'C:/Users/JangtangE/Documents/dataset/train/{label}'

    # 이미지 복사할 경로
    if label is not None:
        output_path = os.path.join('C:/Users/JangtangE/Documents/dataset/labeled_images', label)
        shutil.copy(image_path, output_path)

print('라벨이 있는 이미지 저장이 완료되었습니다.')

라벨이 있는 이미지 저장이 완료되었습니다.

In [ ]:
import cv2
import os
import pandas as pd
import numpy as np

# 주어진 데이터프레임에서 bbox 좌표와 파일명을 가져옵니다.
bbox_df = label_total[['bbox', 'file_name']]

# 빈 리스트를 생성하여 모든 디스크립터를 저장할 준비를 합니다.
all_descriptors = []

# 이미지 폴더의 이미지를 하나씩 처리합니다.
for index, row in bbox_df.iterrows():
    # 이미지 파일을 읽어옵니다.
    image_path = f"C:/Users/JangtangE/Documents/dataset/labeled_images/{row['file_name']}"
    image = cv2.imread(image_path)

    # bbox 좌표를 가져옵니다.
    bbox = row['bbox']
    x, y, width, height = map(int, bbox)

    # bbox 영역에서 물고기를 추출합니다.
    fish_roi = image[y:y+height, x:x+width]

    # SIFT 객체 생성
    sift = cv2.SIFT_create()

    # 키 포인트와 디스크립터 추출
    keypoints, descriptors = sift.detectAndCompute(fish_roi, None)

    # 디스크립터가 없는 경우 무시
    if descriptors is None:
        continue

    # 현재 이미지의 디스크립터를 모든 디스크립터 리스트에 추가
    all_descriptors.append(descriptors)

# 모든 디스크립터를 하나의 Numpy 배열로 병합
all_descriptors_array = np.vstack(all_descriptors)

# Numpy 배열을 데이터프레임으로 변환
descriptor_df = pd.DataFrame(all_descriptors_array)

# 결과 데이터프레임 출력
print(descriptor_df)

          0    1      2     3    4     5     6     7      8     9    ...  \
0         0.0  0.0    0.0   0.0  1.0   0.0   0.0   0.0    0.0   0.0  ...
1       102.0  3.0    0.0   0.0  0.0   0.0   0.0  25.0   77.0   3.0  ...
2        71.0  1.0    0.0   0.0  0.0   0.0   1.0  13.0  165.0   2.0  ...
3        64.0  1.0    1.0   2.0  0.0   0.0   0.0  28.0   95.0   4.0  ...
4         8.0  0.0    0.0   0.0  0.0   0.0   0.0   9.0  145.0  10.0  ...
...       ...  ...    ...   ...  ...   ...   ...   ...    ...   ...  ...
132683    0.0  3.0  107.0  62.0  6.0   0.0   0.0   0.0    1.0   3.0  ...
132684    0.0  0.0    0.0   0.0  6.0  91.0  90.0   2.0    1.0   4.0  ...
132685   60.0  2.0    0.0   0.0  0.0   0.0   0.0   4.0  134.0  68.0  ...
132686    0.0  0.0    0.0   0.0  0.0   0.0   7.0  13.0    1.0   0.0  ...
132687    1.0  0.0    0.0   0.0  3.0  23.0  87.0  17.0   13.0   0.0  ...

          118   119   120    121   122   123    124    125    126   127
0        63.0  22.0   0.0    0.0   3.0  60.0   29.0    5.0   18.0  17.0
1        20.0  28.0   0.0    0.0   0.0   0.0   65.0   45.0    2.0   3.0
2         0.0   5.0   2.0    2.0   0.0   0.0   70.0   19.0    0.0   0.0
3         0.0   1.0   0.0    0.0   2.0  65.0  133.0    0.0    0.0   0.0
4         2.0  65.0   6.0    0.0   0.0   0.0  127.0   43.0    1.0   4.0
...       ...   ...   ...    ...   ...   ...    ...    ...    ...   ...
132683   61.0  22.0   0.0    0.0   0.0   0.0   39.0  112.0    6.0   0.0
132684    1.0   2.0  34.0  115.0  28.0   0.0    0.0    0.0    0.0   1.0
132685  134.0  87.0   8.0    0.0   0.0   0.0    1.0   10.0  134.0  79.0
132686   73.0  48.0   0.0    0.0   0.0   0.0   35.0   65.0   41.0  17.0
132687   38.0  79.0  15.0    8.0  54.0  84.0   11.0    2.0    3.0  11.0

[132688 rows x 128 columns]

In [ ]:
descriptor_df.to_csv(r'C:/Users/JangtangE/Documents/dataset/descriptor_df.csv', index=False)

In [ ]:
import cv2
import numpy as np
import pandas as pd

def extract_features(image):
    # 이미지를 그레이스케일로 변환합니다.
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # 색상 특성 추출
    mean_color = np.mean(image, axis=(0, 1)) # RGB 색상 평균 계산
    std_color = np.std(image, axis=(0, 1))  # RGB 색상 표준 편차 계산
    max_color = np.max(image, axis=(0, 1))  # RGB 색상 최댓값 계산
    mode_color = np.argmax(np.bincount(image.reshape(-1, 3).astype(int).flatten()), axis=0)  # RGB 색상 최빈값 계산

    # 밝기 특성 추출
    mean_brightness = np.mean(gray)
    std_brightness = np.std(gray)

    # 명암 특성 추출
    laplacian = cv2.Laplacian(gray, cv2.CV_64F).var()
    hist = cv2.calcHist([gray], [0], None, [256], [0, 256]) # 명암 히스토그램

    # 크기 특성 추출
    size = image.shape[0] * image.shape[1]

    # 추출한 특성을 딕셔너리로 저장하여 반환합니다.
    features = {'mean_color': mean_color, 'std_color': std_color, 'max_color': max_color, 'mode_color': mode_color,
                'mean_brightness': mean_brightness, 'std_brightness': std_brightness, 'laplacian': laplacian,
                'histogram': hist, 'size': size}
    return features


# 주어진 데이터프레임에서 bbox 좌표와 파일명을 가져옵니다.
bbox_df = label_total[['bbox', 'file_name']]

# 새로운 데이터프레임을 저장할 리스트를 생성합니다.
new_df = []

# 각 이미지에 대해 물고기의 특성을 추출합니다.
for index, row in bbox_df.iterrows():
    # 이미지 파일을 읽어옵니다.
    image_path = f"C:/Users/JangtangE/Documents/dataset/labeled_images/{row['file_name']}"
    image = cv2.imread(image_path)

    # bbox 좌표를 가져옵니다.
    bbox = row['bbox']
    x, y, width, height = map(int, bbox)

    # bbox 영역에서 물고기를 추출합니다.
    fish_roi = image[y:y+height, x:x+width]

    # 물고기의 특성을 추출하여 수치화합니다.
    feature = extract_features(fish_roi)

    # 새로운 데이터프레임에 특성과 파일명을 추가합니다.
    new_row = {'file_name': row['file_name']}
    new_row.update(feature)
    new_df.append(new_row)

# 새로운 데이터프레임을 생성합니다.
new_df = pd.DataFrame(new_df)

In [ ]:
new_df

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 new_df                                                                                       │
│   2                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
NameError: name 'new_df' is not defined

In [ ]:
new_df.to_csv(r'C:/Users/JangtangE/Documents/dataset/new_df.csv', index=False)

In [ ]:
print(label_total['bbox'][0])

[37.98, 209.94, 369.19, 110.89]

In [ ]:
import sys
ros_path = r'C:/Users/JangtangE/Documents/dataset\labeled_images'
if ros_path in sys.path:
    sys.path.remove(ros_path)
import cv2
sys.path.append(r'C:/Users/JangtangE/Documents/dataset\labeled_images')

def main():

    # import image
    img = cv2.imread('C:/Users/JangtangE/Documents/dataset/labeled_images/train_0.png')
    x, y, width, height = label_total['bbox'][0]

    # bbox 영역에서 물고기를 추출합니다.
    x, y, width, height = map(int, label_total['bbox'][0])

    sift_result = None

    # Initiate SIFT detector
    sift = cv2.SIFT_create()

    # find the keypoints and descriptors with SIFT
    # kp = keypoints
    # des = descriptors
    kp, des = sift.detectAndCompute(fish_roi,None)

    # overlay the keypoints on the img
    sift_result = cv2.drawKeypoints(fish_roi, kp, sift_result, (255, 0, 0))

    cv2.imshow('sift_result', sift_result)

    cv2.waitKey(0)
    cv2.destroyAllWindows()


if __name__ == "__main__":
    main()

## Autogluon

In [ ]:
import torch

torch.__version__

'1.12.1+cu113'

In [ ]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
from sklearn.model_selection import train_test_split


# image Data를 다루기 때문에 아래 라이브러리를 호출
from autogluon.multimodal import MultiModalPredictor
import uuid

In [ ]:
# 데이터 프레임 로드
data = pd.read_csv(r'C:/Users/JangtangE/Documents/dataset/label_total.csv')

# 데이터 프레임 내의 이미지 파일 경로 수정
data['image_path'] = 'C:/Users/JangtangE/Documents/dataset/labeled_images/' + data['file_name']

# 레이블 열 이름 설정
# label_column = 'category_id'
label_column = 'name'

# 데이터를 train 및 test로 분할
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

In [ ]:
data

,id,width,height,file_name,category_id,area,bbox,attributes,name,image_path
0,1,640,480,train_0.png,3,40939.4791,"[37.98, 209.94, 369.19, 110.89]","{'occluded': False, 'rotation': 0.0}",강준치,C:/Users/JangtangE/Documents/dataset/labeled_i...
1,283,640,480,train_185.png,5,50205.8704,"[57.07, 247.17, 384.16, 130.69]","{'occluded': False, 'rotation': 0.0}",잉어,C:/Users/JangtangE/Documents/dataset/labeled_i...
2,284,640,480,train_186.png,5,58850.5182,"[96.59, 236.87, 427.01, 137.82]","{'occluded': False, 'rotation': 0.0}",잉어,C:/Users/JangtangE/Documents/dataset/labeled_i...
3,292,640,480,train_192.png,5,62936.7565,"[154.41, 254.3, 467.41, 134.65]","{'occluded': False, 'rotation': 0.0}",잉어,C:/Users/JangtangE/Documents/dataset/labeled_i...
4,297,640,480,train_194.png,5,70061.3550,"[26.18, 222.61, 409.5, 171.09]","{'occluded': False, 'rotation': 0.0}",잉어,C:/Users/JangtangE/Documents/dataset/labeled_i...
...,...,...,...,...,...,...,...,...,...,...
6296,149637,640,480,train_104755.png,3,35322.5680,"[35.18, 94.18, 347.8, 101.56]","{'occluded': False, 'rotation': 0.0}",강준치,C:/Users/JangtangE/Documents/dataset/labeled_i...
6297,149677,640,480,train_104784.png,6,35145.8160,"[52.77, 93.05, 300.7, 116.88]","{'occluded': False, 'rotation': 0.0}",붕어,C:/Users/JangtangE/Documents/dataset/labeled_i...
6298,149678,640,480,train_104785.png,6,35356.5710,"[285.39, 78.86, 296.74, 119.15]","{'occluded': False, 'rotation': 0.0}",붕어,C:/Users/JangtangE/Documents/dataset/labeled_i...
6299,149790,640,480,train_104856.png,0,26736.6856,"[255.89, 216.74, 263.26, 101.56]","{'occluded': False, 'rotation': 0.0}",농어,C:/Users/JangtangE/Documents/dataset/labeled_i...
6300,149791,640,480,train_104857.png,0,14874.5205,"[476.03, 241.7, 162.83, 91.35]","{'occluded': False, 'rotation': 0.0}",농어,C:/Users/JangtangE/Documents/dataset/labeled_i...

In [ ]:
# 모델 저장 경로 정의
model_path = f"./tmp/{uuid.uuid4().hex}-automm_custom"

# MultiModalPredictor 초기화
predictor = MultiModalPredictor(label=label_column, path=model_path)

# 모델 학습
predictor.fit(train_data=train_data)

AutoGluon infers your prediction problem is: 'multiclass' (because dtype of label-column == object).
	8 unique label values:  ['붕어', '강준치', '숭어', '베스', '누치', '잉어', '농어', '블루길']
	If 'multiclass' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])

Global seed set to 0
AutoMM starts to create your model. ✨

- AutoGluon version is 0.8.2.

- Pytorch version is 1.12.1+cu113.

- Model will be saved to "c:\Users\JangtangE\Downloads\tmp\5967b72102c041c4b3ae191897783ab8-automm_custom".

- Validation metric is "accuracy".

- To track the learning progress, you can open a terminal and launch Tensorboard:
    ```shell
    # Assume you have installed tensorboard
    tensorboard --logdir c:\Users\JangtangE\Downloads\tmp\5967b72102c041c4b3ae191897783ab8-automm_custom
    ```

Enjoy your coffee, and let AutoMM do the job ☕☕☕ Learn more at https://auto.gluon.ai

1 GPUs are detected, and 1 GPUs will be used.
   - GPU 0 name: NVIDIA GeForce RTX 2080 Ti
   - GPU 0 memory: 10.61GB/11.81GB (Free/Total)
CUDA version is 11.3.

Using 16bit None Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name              | Type                | Params
----------------------------------------------------------
0 | model             | MultimodalFusionMLP | 198 M
1 | validation_metric | MulticlassAccuracy  | 0
2 | loss_func         | CrossEntropyLoss    | 0
----------------------------------------------------------
198 M     Trainable params
0         Non-trainable params
198 M     Total params
396.041   Total estimated model params size (MB)

Sanity Checking: 0it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Epoch 0, global step 17: 'val_accuracy' reached 0.80159 (best 0.80159), saving model to 'C:\\Users\\JangtangE\\Downloads\\tmp\\5967b72102c041c4b3ae191897783ab8-automm_custom\\epoch=0-step=17.ckpt' as top 3

Validation: 0it [00:00, ?it/s]

Epoch 0, global step 35: 'val_accuracy' reached 0.95635 (best 0.95635), saving model to 'C:\\Users\\JangtangE\\Downloads\\tmp\\5967b72102c041c4b3ae191897783ab8-automm_custom\\epoch=0-step=35.ckpt' as top 3

Validation: 0it [00:00, ?it/s]

Epoch 1, global step 53: 'val_accuracy' reached 0.99206 (best 0.99206), saving model to 'C:\\Users\\JangtangE\\Downloads\\tmp\\5967b72102c041c4b3ae191897783ab8-automm_custom\\epoch=1-step=53.ckpt' as top 3

Validation: 0it [00:00, ?it/s]

Epoch 1, global step 71: 'val_accuracy' reached 1.00000 (best 1.00000), saving model to 'C:\\Users\\JangtangE\\Downloads\\tmp\\5967b72102c041c4b3ae191897783ab8-automm_custom\\epoch=1-step=71.ckpt' as top 3
Start to fuse 3 checkpoints via the greedy soup algorithm.

Predicting: 0it [00:00, ?it/s]

Predicting: 0it [00:00, ?it/s]

Predicting: 0it [00:00, ?it/s]

AutoMM has created your model 🎉🎉🎉

- To load the model, use the code below:
    ```python
    from autogluon.multimodal import MultiModalPredictor
    predictor = MultiModalPredictor.load("c:\Users\JangtangE\Downloads\tmp\5967b72102c041c4b3ae191897783ab8-automm_custom")
    ```

- You can open a terminal and launch Tensorboard to visualize the training log:
    ```shell
    # Assume you have installed tensorboard
    tensorboard --logdir c:\Users\JangtangE\Downloads\tmp\5967b72102c041c4b3ae191897783ab8-automm_custom
    ```

- If you are not satisfied with the model, try to increase the training time,
adjust the hyperparameters (https://auto.gluon.ai/stable/tutorials/multimodal/advanced_topics/customization.html),
or post issues on GitHub: https://github.com/autogluon/autogluon

In [ ]:
# 테스트 데이터에 대한 예측 성능 평가
scores = predictor.evaluate(test_data, metrics=["accuracy"])
print('Top-1 test accuracy: %.3f' % scores["accuracy"])

Predicting: 0it [00:00, ?it/s]

Top-1 test accuracy: 0.998

In [ ]:
# 각각의 모델의 훈련 성능을 평가할 수 있음
test_data = task.Dataset(dataframe=test_data, path=image_path)
test_performance = predictor.evaluate(test_data)
print(test_performance)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:2                                                                                    │
│                                                                                                  │
│   1 # 각각의 모델의 훈련 성능을 평가할 수 있음                                                   │
│ ❱ 2 test_data = task.Dataset(dataframe=test_data, path=image_path)                               │
│   3 test_performance = predictor.evaluate(test_data)                                             │
│   4 print(test_performance)                                                                      │
│   5                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
NameError: name 'task' is not defined

### 전체 데이터(null 값있음)

In [ ]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
from sklearn.model_selection import train_test_split

# image Data를 다루기 때문에 아래 라이브러리를 호출
from autogluon.multimodal import MultiModalPredictor
import uuid

In [ ]:
# 전체 데이터 프레임 가져오기
train= label_df.copy()
train = train.drop(['flickr_url', 'coco_url', 'id_x', 'supercategory', 'segmentation', 'attributes'], axis=1)
train

,id,width,height,file_name,license,date_captured,image_id,category_id,area,bbox,iscrowd,id_y,name
0,1,640,480,train_0.png,0,0,1,3,40939.4791,"[37.98, 209.94, 369.19, 110.89]",0,3.0,강준치
185,283,640,480,train_185.png,0,0,283,5,50205.8704,"[57.07, 247.17, 384.16, 130.69]",0,5.0,잉어
186,284,640,480,train_186.png,0,0,284,5,58850.5182,"[96.59, 236.87, 427.01, 137.82]",0,5.0,잉어
192,292,640,480,train_192.png,0,0,292,5,62936.7565,"[154.41, 254.3, 467.41, 134.65]",0,5.0,잉어
194,297,640,480,train_194.png,0,0,297,5,70061.3550,"[26.18, 222.61, 409.5, 171.09]",0,5.0,잉어
...,...,...,...,...,...,...,...,...,...,...,...,...,...
105495,149637,640,480,train_104755.png,0,0,149637,3,35322.5680,"[35.18, 94.18, 347.8, 101.56]",0,3.0,강준치
105524,149677,640,480,train_104784.png,0,0,149677,6,35145.8160,"[52.77, 93.05, 300.7, 116.88]",0,6.0,붕어
105525,149678,640,480,train_104785.png,0,0,149678,6,35356.5710,"[285.39, 78.86, 296.74, 119.15]",0,6.0,붕어
105596,149790,640,480,train_104856.png,0,0,149790,0,26736.6856,"[255.89, 216.74, 263.26, 101.56]",0,0.0,농어
105597,149791,640,480,train_104857.png,0,0,149791,0,14874.5205,"[476.03, 241.7, 162.83, 91.35]",0,0.0,농어

In [ ]:
train['image_id']= train['image_id'].fillna('0').astype(int)
train['category_id']= train['category_id'].fillna('-1').astype(int)
train['area']= train['area'].fillna('0.0')
train['bbox']= train['bbox'].fillna('0000')
train['bbox_x'] = train['bbox'].apply(lambda x: x[0])
train['bbox_y'] = train['bbox'].apply(lambda x: x[1])
train['bbox_w'] = train['bbox'].apply(lambda x: x[2])
train['bbox_h'] = train['bbox'].apply(lambda x: x[3])
train['iscrowd']= train['iscrowd'].fillna('-1').astype(int)
train['id_y']= train['id_y'].fillna('0').astype(int)
train['name']= train['name'].fillna('없음')

train = train.drop(columns='bbox', axis=1)
train

,id,width,height,file_name,license,date_captured,image_id,category_id,area,iscrowd,id_y,name,bbox_x,bbox_y,bbox_w,bbox_h
0,1,640,480,train_0.png,0,0,1,3,40939.4791,0,3,강준치,37.98,209.94,369.19,110.89
185,283,640,480,train_185.png,0,0,283,5,50205.8704,0,5,잉어,57.07,247.17,384.16,130.69
186,284,640,480,train_186.png,0,0,284,5,58850.5182,0,5,잉어,96.59,236.87,427.01,137.82
192,292,640,480,train_192.png,0,0,292,5,62936.7565,0,5,잉어,154.41,254.30,467.41,134.65
194,297,640,480,train_194.png,0,0,297,5,70061.3550,0,5,잉어,26.18,222.61,409.50,171.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105495,149637,640,480,train_104755.png,0,0,149637,3,35322.5680,0,3,강준치,35.18,94.18,347.80,101.56
105524,149677,640,480,train_104784.png,0,0,149677,6,35145.8160,0,6,붕어,52.77,93.05,300.70,116.88
105525,149678,640,480,train_104785.png,0,0,149678,6,35356.5710,0,6,붕어,285.39,78.86,296.74,119.15
105596,149790,640,480,train_104856.png,0,0,149790,0,26736.6856,0,0,농어,255.89,216.74,263.26,101.56
105597,149791,640,480,train_104857.png,0,0,149791,0,14874.5205,0,0,농어,476.03,241.70,162.83,91.35

In [ ]:
# 데이터 프레임 내의 이미지 파일 경로 수정
train['image_path'] = 'C:/Users/guscldns/Downloads/dataset/train/' + train['file_name']

# 데이터를 train 및 test로 분할
train_data, test_data = train_test_split(train, test_size=0.2, random_state=42)

In [ ]:
# 모델 저장 경로 정의
model_path = f"./tmp/{uuid.uuid4().hex}-automm_custom"

# 모델 학습
predictor = MultiModalPredictor(label='name', path=model_path, eval_metric='f1_macro').fit(train_data=train_data, time_limit=30)

AutoGluon infers your prediction problem is: 'multiclass' (because dtype of label-column == object).
	8 unique label values:  ['붕어', '강준치', '숭어', '베스', '누치', '잉어', '농어', '블루길']
	If 'multiclass' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Global seed set to 0
AutoMM starts to create your model. ✨

- AutoGluon version is 0.8.2.

- Pytorch version is 1.12.1+cu113.

- Model will be saved to "c:\Users\JangtangE\Downloads\tmp\1a9bc9c84ffa48a4bd6ded841df8e8a4-automm_custom".

- Validation metric is "accuracy".

- To track the learning progress, you can open a terminal and launch Tensorboard:
    ```shell
    # Assume you have installed tensorboard
    tensorboard --logdir c:\Users\JangtangE\Downloads\tmp\1a9bc9c84ffa48a4bd6ded841df8e8a4-automm_custom
    ```

Enjoy your coffee, and let AutoMM do the job ☕☕☕ Learn more at https://auto.gluon.ai

1 GPUs are detected, and 1 GPUs will be used.
   - GPU 0 name: NVIDIA GeForce RTX 2080 Ti
   - GPU 0 memory: 9.69GB/11.81GB (Free/Total)
CUDA version is 11.3.

Using 16bit None Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name              | Type                | Params
----------------------------------------------------------
0 | model             | MultimodalFusionMLP | 109 M
1 | validation_metric | MulticlassAccuracy  | 0
2 | loss_func         | CrossEntropyLoss    | 0
----------------------------------------------------------
109 M     Trainable params
0         Non-trainable params
109 M     Total params
219.581   Total estimated model params size (MB)

Sanity Checking: 0it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Epoch 0, global step 17: 'val_accuracy' reached 0.67460 (best 0.67460), saving model to 'C:\\Users\\JangtangE\\Downloads\\tmp\\1a9bc9c84ffa48a4bd6ded841df8e8a4-automm_custom\\epoch=0-step=17.ckpt' as top 3
Time limit reached. Elapsed time is 0:00:38. Signaling Trainer to stop.

Validation: 0it [00:00, ?it/s]

AutoMM has created your model 🎉🎉🎉

- To load the model, use the code below:
    ```python
    from autogluon.multimodal import MultiModalPredictor
    predictor = MultiModalPredictor.load("c:\Users\JangtangE\Downloads\tmp\1a9bc9c84ffa48a4bd6ded841df8e8a4-automm_custom")
    ```

- You can open a terminal and launch Tensorboard to visualize the training log:
    ```shell
    # Assume you have installed tensorboard
    tensorboard --logdir c:\Users\JangtangE\Downloads\tmp\1a9bc9c84ffa48a4bd6ded841df8e8a4-automm_custom
    ```

- If you are not satisfied with the model, try to increase the training time,
adjust the hyperparameters (https://auto.gluon.ai/stable/tutorials/multimodal/advanced_topics/customization.html),
or post issues on GitHub: https://github.com/autogluon/autogluon

In [ ]:
# 각각의 모델의 훈련 성능을 평가할 수 있음
ld_board = predictor.leaderboard(train, silent=True)

ld_board

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:2                                                                                    │
│                                                                                                  │
│   1 # 각각의 모델의 훈련 성능을 평가할 수 있음                                                   │
│ ❱ 2 ld_board = predictor.leaderboard(train, silent=True)                                         │
│   3                                                                                              │
│   4 ld_board                                                                                     │
│   5                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'MultiModalPredictor' object has no attribute 'leaderboard'